[package]
name = "convexfx-oracle"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
convexfx-types = { path = "../convexfx-types" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]


