[package]
name = "convexfx-fees"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
convexfx-types = { path = "../convexfx-types" }
convexfx-risk = { path = "../convexfx-risk" }
serde = { workspace = true }

[dev-dependencies]


